#:schema node_modules/wrangler/config-schema.json
name = "framer-dribbble-plugin-oauth"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { binding = "keyValueStore", id = "9d5b0496db62419f97c2616f4821c18e" },
]

[vars]
PLUGIN_PARENT_DOMAIN = "plugins.framercdn.com"
